import { existsSync, readFileSync, writeFileSync, mkdirSync, cpSync, chmodSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { run } from '../lib/shell.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const CONFIGS_DIR = join(__dirname, '..', 'configs');
const DOTFILES_DIR = join(__dirname, '..', 'dotfiles');

export default {
  name: 'shortcuts',
  order: 5,
  description: 'Terminal shortcuts & aliases',
  dependencies: ['system-prereqs'],

  async detect() {
    const home = process.env.HOME;
    const zshrc = existsSync(join(home, '.zshrc')) ? readFileSync(join(home, '.zshrc'), 'utf8') : '';
    const hasSource = zshrc.includes('.dmdfami/shortcuts.sh');
    const hasBin = existsSync(join(home, 'bin', 'mac'));
    return { installed: hasSource && hasBin, details: `source: ${hasSource ? 'ok' : 'missing'}, ~/bin: ${hasBin ? 'ok' : 'missing'}` };
  },

  async install() {
    const home = process.env.HOME;

    // 1. Generate shortcuts.sh from aliases.json
    const dmdfamiDir = join(home, '.dmdfami');
    mkdirSync(dmdfamiDir, { recursive: true });
    const aliases = JSON.parse(readFileSync(join(CONFIGS_DIR, 'aliases.json'), 'utf8'));
    const shortcutsContent = generateShortcutsScript(aliases);
    writeFileSync(join(dmdfamiDir, 'shortcuts.sh'), shortcutsContent, { mode: 0o644 });

    // 2. Add source line to .zshrc (never overwrite)
    const zshrcPath = join(home, '.zshrc');
    const zshrc = existsSync(zshrcPath) ? readFileSync(zshrcPath, 'utf8') : '';
    const sourceLine = '[ -f ~/.dmdfami/shortcuts.sh ] && source ~/.dmdfami/shortcuts.sh';
    if (!zshrc.includes('.dmdfami/shortcuts.sh')) {
      writeFileSync(zshrcPath, zshrc + (zshrc.endsWith('\n') ? '' : '\n') + sourceLine + '\n');
    }

    // 3. Copy ~/bin/ scripts
    const binDir = join(home, 'bin');
    mkdirSync(binDir, { recursive: true });
    const binSrc = join(DOTFILES_DIR, 'bin');
    if (existsSync(binSrc)) {
      for (const file of ['mac', 'qall']) {
        const src = join(binSrc, file);
        if (existsSync(src)) {
          cpSync(src, join(binDir, file));
          chmodSync(join(binDir, file), 0o755);
        }
      }
    }

    console.log('\n    Shortcuts installed. Open new terminal to activate.');
  },

  async verify() {
    const home = process.env.HOME;
    const zshrc = existsSync(join(home, '.zshrc')) ? readFileSync(join(home, '.zshrc'), 'utf8') : '';
    return zshrc.includes('.dmdfami/shortcuts.sh');
  },
};

function generateShortcutsScript(aliases) {
  let script = '#!/bin/bash\n# Generated by dmdfami/setup — do not edit manually\n\n';

  // Aliases (escape single quotes in values)
  script += '# Aliases\n';
  for (const [name, value] of Object.entries(aliases.aliases || {})) {
    const escaped = value.replace(/'/g, "'\\''");
    script += `alias ${name}='${escaped}'\n`;
  }

  // Functions
  script += '\n# Functions\n';
  for (const [name, body] of Object.entries(aliases.functions || {})) {
    script += `${name}() { ${body} }\n`;
  }

  // PATH additions
  script += '\n# PATH\n';
  script += 'export PATH="$HOME/bin:$PATH"\n';

  return script;
}
